version: 0.1

phases:
  pre_build:
    commands:
      - npm install --no-optional
      - npm test
  build:
    commands:
      - npm run webpack
artifacts:
  files:
    - index.html
    - favicon.ico
    - styles/main.css
    - dist/bundle.js
    - docs/*
    - images/*
